### ISSUE TITLE
Multiple video streams from one source?

### ISSUE THREAD

**Issue by andrew103** [dkumor/rtcbot#11]
The project I'm working on requires the use of multiple cameras on the robot. Is there a way to implement multiple video streams from one source? Is it just a matter of sending a JSON packet continuously with the frames instead of using the conn.video.putSubscription function?

I know it can be done, but I'm having a hard time figuring out how to do so with this library. Any help would be greatly appreciated.

**Comment by andrew103** [comment]
Ah gotcha. That seems to cover the robot side with python, but it seems the javascript API isn't setup for multiple tracks yet. From `js/src/connection.js` -
```
  _onTrack(track) {
    // This is the internal track receiver. Right now only supports a single incoming stream.
    this.incomingStream = track.streams[0];
    if (this._callback != null) {
      this._callback(track.streams[0]);
    }
  }
```
There's also no public facing methods for getting/adding tracks in the JS API it seems

**Comment by andrew103** [comment]
Also, I'm getting an error when trying to add multiple tracks that occurs when the client and server are exchanging offer/answer. Stack trace below:
```
[2020-06-10 16:46:30,823] ERROR in app: Exception on request POST /connect
Traceback (most recent call last):
  File "/home/jetson0/.local/lib/python3.6/site-packages/quart/app.py", line 1451, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/home/jetson0/.local/lib/python3.6/site-packages/quart/app.py", line 1473, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/home/jetson0/.local/lib/python3.6/site-packages/quart/app.py", line 892, in handle_user_exception
    raise error
  File "/home/jetson0/.local/lib/python3.6/site-packages/quart/app.py", line 1471, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/jetson0/.local/lib/python3.6/site-packages/quart/app.py", line 1519, in dispatch_request
    return await handler(**request_.view_args)
  File "rtcbot_flask.py", line 149, in connect
    serverResponse = await conn.getLocalDescription(clientOffer)
  File "/usr/local/lib/python3.6/dist-packages/rtcbot/connection.py", line 371, in getLocalDescription
    await self._rtc.setLocalDescription(answer)
  File "/home/jetson0/.local/lib/python3.6/site-packages/aiortc/rtcpeerconnection.py", line 721, in setLocalDescription
    t._currentDirection = and_direction(t.direction, t._offerDirection)
  File "/home/jetson0/.local/lib/python3.6/site-packages/aiortc/rtcpeerconnection.py", line 238, in and_direction
    return sdp.DIRECTIONS[sdp.DIRECTIONS.index(a) & sdp.DIRECTIONS.index(b)]
ValueError: None is not in list
```
Note that I'm using `quart` instead of `aiohttp` for my web server (which is just `flask` with async capabilities essentially)

**Comment by dkumor** [comment]
I'll try to see if I can reproduce this when I add multiple video tracks to the javascript code.

**Comment by andrew103** [comment]
Any updates with regard to this?

**Comment by dkumor** [comment]
Unfortunately, a deadline is requiring my attention at the moment, so everything else has to wait :(
I hopefully I'll be free later this week.

**Comment by andrew103** [comment]
Gotcha, no worries!

**Comment by dkumor** [comment]
I have opened an upstream issue (https://github.com/aiortc/aiortc/issues/382) which will need to be resolved before rtcbot can handle multiple video streams.

**Comment by beniroquai** [comment]
Hey, is there any update on this? Would also be very interested to have multiple streams per camera instance! 
Awesome project! Thanks!

**Comment by dkumor** [comment]
This issue is actually focused on the reversed problem: sending multiple camera different streams to one client using a single connection. 

You can send a camera stream to multiple targets by subscribing multiple targets to the camera - that should work without any issues.

**Comment by Mohit-Ak** [comment]
Has this been resolved? If so can you please post a sample(example) of client and server implementation?

**Comment by dkumor** [comment]
I believe that I fixed the rtcbot portion of the issue before the corresponding upstream issue was fixed, so the code is there, but untested. I should have a bit of time in ~2 weeks to test it and add a tutorial/instructions of use.

**Comment by danielkoohmarey-bc** [comment]
Following up on this, do we have any multi stream instructions available?

**Comment by dkumor** [comment]
Not yet, unfortunately, thanks for the reminder!

**Comment by danielkoohmarey-bc** [comment]
> Not yet, unfortunately, thanks for the reminder!

Wishing everyone happy holidays & this would still be very useful! Thanks!

**Comment by marakhi** [comment]
Hello, Just wanted to see if there is any update on this. @dkumor, I want to try stopgap solution you suggested above to send one 'big' frame by combining 2 camera frames side by side but not sure how it will work. I started with basic approach as shown below but on browser side I don't see any video (I am just sending frames from single camera). Before I combine frames from 2 camera I need to resolve single camera feed issue.
 
```
# commented below line and replace it with camera.subscribe 
#conn.video.putSubscription(camera)

@camera.subscribe
def onFrame(frame):
   #below code line show video output on display
    display.put_nowait(frame)    
   #below code line doesn't show video output on browser.  Though it is not generating any error on robot or server side.  
    conn.video.put_nowait(frame)
```

**Comment by dkumor** [comment]
Can you open a separate issue for this? I don't think this problem is related to multiple video feeds.

**Comment by marakhi** [comment]
@dkumor, Thank you very much for helping. I am looking for multi video feed solution but meanwhile if there is any intermediate solution to merge frames from 2 or more cameras then that will work too. Let me go ahead and create new issue per your suggestion. Thank you.
