### ISSUE TITLE
awaiting a future attached to a different loop

### ISSUE THREAD

**Issue by jensbjorgensen** [dkumor/rtcbot#43]
Running on a recent raspberry pi, I tried to run the script under the tutorial heading

Talking to Python from the Browser

Once I open the link in the browser the script begins rapidly spewing errors of the form:

RuntimeError: Task <Task pending name='Task-11627' coro=<Queue.get() running at /usr/lib/python3.9/asyncio/queues.py:166> cb=[<TaskWakeupMethWrapper object at 0xa8a25a18>()]> got Future <Future pending> attached to a different loop
Got unrecognized error from task. ignoring:
Traceback (most recent call last):
  File "/home/pi/src/rtcbot/rtcbot/base/base.py", line 365, in _get
    await self._getTask
  File "/usr/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter

As the src path suggests, I've pulled latest git in case this was somehow recently fixed. 

Looking at the code in base.py around 365, self._getTask created just above it, should yield the same loop where await is called on 365 so I'm a bit confused about the error. But that's the error .... not sure what to make of it.

**Comment by jensbjorgensen** [comment]
Actually having just typed it, actually I think it does make sense. The Queue is created in a different loop than where it was awaited. I'm not familiar with the code yet but I'll dig around.

**Comment by dkumor** [comment]
This is surprising - as I understand it, you are using the tutorial code without modification? I will need to check if anything changed in Python 3.9 that might have caused the issue.

**Comment by jensbjorgensen** [comment]
yes, I copied pasted the code there verbatim. I'm running Raspbian 11, the python I'm using is the stock distro version

Python 3.9.2 (default, Mar 12 2021, 04:06:34) 
[GCC 10.2.1 20210110] on linux

**Comment by dkumor** [comment]
I have confirmed the issue on pi 4 with latest raspbian. I don't know if I will have time to look into it this weekend, so it might be a week or two before I can fix it.

**Comment by dkumor** [comment]
It looks like `get_event_loop` is being deprecated. I have fixed the issue on my end by adding the following code to the top of the file:
```python
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
```

and then setting the loop manually:
```python
conn = RTCConnection(loop=loop)
web.run_app(app,loop=loop)
```

I will try to fix this more deeply.

**Comment by beniroquai** [comment]
Hey @dkumor thanks for your effort to keep this project alive! I'm returning back to webrtc ;-) 
Did you have a chance to look into this already? I can confirm this issue on python3.9 on my mac, too.

**Comment by beniroquai** [comment]
Quick update: I tested the code on python3.8 and it shows the same behaviour. Perhaps a downgrade or aiohttp may help?
